### ISSUE TITLE
expiry clarification

### ISSUE THREAD

**Issue by jzacharuk** [wyattjoh/rate-limit-redis#1]
Hi, 

Can you explain to me the difference between 
express-rate-limit windowMs and rate-limit-redis expiry? 

**windowMs**: milliseconds - how long to keep records of requests in memory. Defaults to 60000 (1 minute).

**expiry**: seconds - how long each rate limiting window exists for. Defaults to 60.

Does one of these override the other? Or should they be set the same? Or do they do completely different things?

**Comment by Ziao** [comment]
I'd like to know the same. I've set them to the same value for now and it seems to work alright, in fact, I think this one would override the other one, but haven't looked into the code yet.

**Comment by wyattjoh** [comment]
Glad to help clarify @jzacharuk + @Ziao! The `expiry` here is used to control the time for which the first hit will count for during the rate limiting session. An example could be, `expiry = 5`:

```
11:31:00: First hit
11:31:01: --
11:31:02: --
11:31:03: --
11:31:04: Second hit
11:31:05: --
11:31:06: (the window created from "First hit" has expired, limit reset!)
```

I found this to be a good method to help buffer requests without getting locked out permanently.

Let me know if this helps!!

**Comment by wyattjoh** [comment]
Please re-open if there's any other issues!

**Comment by Diluka** [comment]
So, if I set `expiry` to 60(1 minute) and `windowMs` to 3600000(1 hour), the limiting window will reset after 1 minute not 1 hour? 
I need to manually set `expiry` and `windowMs` matching each other to let `rate-limit` work as expected. Is it right? @wyattjoh

**Comment by mich356c** [comment]
Bit late, but for others who stumble upon this: The answer to @Diluka's question is yes, you need to manually set them both so that they match. Just remember that the `windowMs` option is only used in the default rate-limit handler for `express-rate-limit`, specifically when it sets the `Retry-After` header.

So if you're overwriting the handler anyway, it doesn't really matter.
