### ISSUE TITLE
Configure redis

### ISSUE THREAD

**Issue by waloc** [wyattjoh/rate-limit-redis#10]
Hey, thanks for your plugin.
I have some troubles to configure the plugin with my heroku redis

Here is my config
```
const store = new RedisStore({
	host: redisUrl.hostname, // loremipsum.amazon.com....
	password: redisUrl.auth, // h:dfkjsj27934jkdhfksdfgksjdhé
	port: redisUrl.port // 37259
})
```
Here is the error I get :

`Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED`

Thank your for your help 👍

**Comment by wyattjoh** [comment]
Referring to https://github.com/wyattjoh/rate-limit-redis#configuration, you need to provide a client instance rather than connection details.

```js
// ...
const Redis = require('ioredis');

const store = new RedisStore({
  client: new Redis({
    host: redisUrl.hostname, // loremipsum.amazon.com....
    password: redisUrl.auth, // h:dfkjsj27934jkdhfksdfgksjdhé
    port: redisUrl.port // 37259
  }),
});
```

😄

**Comment by waloc** [comment]
Thank you verymuch it's working !
