### ISSUE TITLE
expiry param make no sense

### ISSUE THREAD

**Issue by idangozlan** [wyattjoh/rate-limit-redis#12]
Since expiry time is already set in the Rate Limit, why should we include it another time for the redis?

I guess that if it's not possible due to the `express-rate-limit` module, we can suggest modification of the implementation for the store driver on the `express-rate-limit`

**Comment by wdetac** [comment]
Totally agree, it is very confusing

**Comment by Tinadim** [comment]
I believe if it's not simple to fix, the `expiracy` param should at least be in milliseconds to be in the same unit as the parameter `windowMs` from `express-rate-limite` and perhaps use the same name? But regardless of changes, this should be mentioned in the docs. The comment in the README file

```
max: 100, // limit each IP to 100 requests per windowMs
```
makes it even more confusing

**Comment by wyattjoh** [comment]
Perfectly understandable!

I'm a bit time limited, so I'd recommend opening a PR with the suggested change to the store driver https://github.com/nfriedly/express-rate-limit so that I can adapt the store to support it!
