### ISSUE TITLE
Fallback store?

### ISSUE THREAD

**Issue by pedroslopez** [wyattjoh/rate-limit-redis#20]
Hello! First of all, thanks for making this module.

Is there a way to use a secondary store (like in-memory) when for whatever reason redis has become unreachable?

**Comment by wyattjoh** [comment]
Based on the design of the underlying package, [express-rate-limit](https://github.com/nfriedly/express-rate-limit), I don't think so. Certainly an interesting idea, but I'm not sure how useful this would be in production given a horizontally distributed deployment, where now each node would have it's own independent store. I would think that if Redis was unavailable that would be a bigger problem ;)
