### ISSUE TITLE
store type error： RedisClient or Redis ？

### ISSUE THREAD

**Issue by CaoMeiYouRen** [wyattjoh/rate-limit-redis#24]
"ioredis": "^4.14.1",
"redis": "^2.8.0",
 "express-rate-limit": "^5.0.0",
"rate-limit-redis": "^1.7.0",
```typescript
//in typescript
import IORedis = require('ioredis'); 
const redis = new IORedis({}) //type:Redis.Redis

import Redis = require('redis'); 
const redisClient = Redis.createClient({})// type:Redis.RedisClient

import RateLimit = require('express-rate-limit')
import RedisStore = require('rate-limit-redis')

const limiter = new RateLimit({
  store: new RedisStore({
    client: client  // need type:  RedisClient
  }),
  max: 100, 
  delayMs: 0 
});
```
So, how to solve it？

**Comment by astr0sl0th** [comment]
Did you find a solution?

**Comment by wyattjoh** [comment]
At the moment, type errors related to typescript types should be addressed on the DefinitlyTyped repo at: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rate-limit-redis

**Comment by CaoMeiYouRen** [comment]
> At the moment, type errors related to typescript types should be addressed on the DefinitlyTyped repo at: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/rate-limit-redis
emmm，ok
