### ISSUE TITLE
Buffer deprecation warning

### ISSUE THREAD

**Issue by npapagna** [wyattjoh/rate-limit-redis#28]
The current `redis` version, `2.8.0`, causes Buffer deprecation warning messages:

`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
`
(it looks like one of `redis` dependencies, `redis-parser 2.6.0`, is the reason this happens).

I understand this was fixed in the [latest version](https://github.com/NodeRedis/node-redis/releases/tag/v3.0.0).

Is there any chance to to bump the `redis` version to avoid these warnings?

**Comment by wyattjoh** [comment]
Thanks for the notification! I've gone ahead and bumped the version! Please check out version 2.0.0 once CI publishes it.
