### ISSUE TITLE
Publish the new version

### ISSUE THREAD

**Issue by doug-martin** [wyattjoh/rate-limit-redis#3]
I would like to use the new `ioredis` functionality however the package doesn't appear to be published with the code from #2 

If you could publish the new version that would be great!

**Comment by wyattjoh** [comment]
For sure! Thanks for the ping, I didn't realize CI wasn't attached to the project. Just published version 1.1.0 https://www.npmjs.com/package/rate-limit-redis

Thanks @doug-martin!
