### ISSUE TITLE
ECONNREFUSED when initializing

### ISSUE THREAD

**Issue by gvko** [wyattjoh/rate-limit-redis#30]
I initialize the redis client connection and then pass it on to the rate limiter, as a new redis store, and I'm getting 
```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)
```

Here's my code:
```
import * as redis from 'redis';
import * as RateLimiter from 'express-rate-limit';
import * as RedisStore from 'rate-limit-redis';

const redisClient = redis.createClient({
    host: config.host,
    port: config.port,
    password: config.password
  });

new RateLimiter({
    store: new RedisStore({
      client: redisClient
    }),
    windowMs,
    max: maxReq
});
```

If I comment out the following part of the code:
```
    store: new RedisStore({
      client: redisClient
    }),
```
then everything initializes fine. And actually I've been using this Redis connection for a few weeks now, before trying to add the rate limiter.

**Comment by atomicman57** [comment]
How did you fix this? @gvko

**Comment by gvko** [comment]
> How did you fix this? @gvko

I think the problem was that the limiter was being initialized before I initialize my actual Redis connection. That is because the function that was wrapping the Redis conn initialization was `async` and the wrapper initializing the RateLimiter was _not_ `async`, therefore finishing first.
What I did was to emit events and thru them synchronise the initialization of the two.
@atomicman57

**Comment by atomicman57** [comment]
Thanks @gvko
