### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by perry-mitchell** [wyattjoh/rate-limit-redis#31]
The docs don't over the example properties in the readme:

```
const limiter = new RateLimit({
  store: new RedisStore({
    client: client
  }),
  max: 100, // limit each IP to 100 requests per windowMs
  delayMs: 0 // disable delaying - full speed until the max limit is reached
});
```

Only `expiry`, `resetExpiryOnChange`, `prefix`, `client` and `redisURL` are listed, and these are presumably for the `store` configuration property. This makes the documentation very confusing imo. `store`, `max` and `delayMs` aren't documented, and `windowMs` (which only appears in a comment) isn't listed either.

Would you consider a PR to fix this?

**Comment by wyattjoh** [comment]
The other configuration listed is actually for the [`express-rate-limit`](https://github.com/nfriedly/express-rate-limit) package. Their configuration is documented [here](https://github.com/nfriedly/express-rate-limit#configuration-options).

I'd definitely consider a PR that clarifies that on the README!
