### ISSUE TITLE
hi, in my local pc I can't have my ip

### ISSUE THREAD

**Issue by jensysantana** [wyattjoh/rate-limit-redis#39]
what I see in redis is: "rl:::ffff:127.0.0.1" but not IP. is this the behavior in development ?

rateLimit({
        windowMs: windowMs || 60 * 60 * 1000,
        max: max || 10,
        handler: handler || expressRateLimitMiddleware,
        store: new RateLimitRedisStore({
            client: redisClient,
            expiry: 10*60*1000, 
            prefix: "rl"
        }),
    })

**Comment by gamemaker1** [comment]
Hi,

By development I assume you mean you are running it on localhost. If yes, then the behaviour you see is correct.

What you see (`rl:::ffff:127.0.0.1`) is basically the `{prefix}{ip}`. Here, the prefix is `rl:` and the IP address is `::ffff:127.0.0.1`. The IP address is both your IPv6 address (`::ffff`) and IPv4 address (`127.0.0.1`), separated by a `:`.

So when you make a request from localhost to a server running on localhost, the IP address sent to express is localhost's IP - `127.0.0.1` or `::ffff`.

When you deploy this on a remote server, you should be able to see your actual IP address (which you can get from https://api.ipify.org/).

Hope this helps.
