### ISSUE TITLE
how to get remaining request ?

### ISSUE THREAD

**Issue by thanhnguyennguyen** [wyattjoh/rate-limit-redis#40]
can you share redis key structures to get maxRequest and remainingRequest ?

**Comment by gamemaker1** [comment]
Hi,

The format for key names in Redis is `{prefix}{identifier}`. The prefix, by default, is `rl:` and the identifier is, by default, the client's IP address.

Also, the middleware adds a `request.rateLimit` property is added to all requests with the `limit`, `current`, and `remaining` number of requests and, if the store provides it, a `resetTime` Date object. See [this](https://github.com/nfriedly/express-rate-limit#request-api) for more information.

Hope this helps.
