### ISSUE TITLE
Redis instance size

### ISSUE THREAD

**Issue by paglias** [wyattjoh/rate-limit-redis#5]
Hi, we're interested in using this software for our server but I'm not sure how bug the redis instance should be. Do you maybe know how much memory is used for every request / ip?

Thanks

**Comment by wyattjoh** [comment]
It shouldn't have a large resource requirement, as it's storing a small amount of data, and this adapter expires those keys after the data isn't relevant anymore. I'd say around 256MB of ram should be sufficient?
