### ISSUE TITLE
ioredis setup

### ISSUE THREAD

**Issue by usmansbk** [wyattjoh/rate-limit-redis#56]
### Description

The `README` example didn't work for `ioredis`.

This is what worked for me:

```js
import Redis from "ioredis";

const redis = new Redis();
const client = redis.createClient();

const rateLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes interval
  max: 2000,
  standardHeaders: true,
  legacyHeaders: false,
  store: new RedisStore({
    sendCommand: (...args) => client.call(...args),
  }),
  delayMs: 0,
});
```

### Library version

"ioredis": "^4.28.3",     "rate-limit-redis": "^3.0.0",

### Node version

v14.18.2

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @usmansbk,

From what I understand (see https://github.com/luin/ioredis/issues/496), the `createClient` method in IORedis is deprecated and you are supposed to use `new Redis()` to create a client. Could you please share the error/problem that occurs when you don't use `createClient`?

Thanks

**Comment by usmansbk** [comment]
@gamemaker1 This is what I get

```js
TypeError: _redis.default.call is not a function
    at RedisStore.sendCommand
```
