### ISSUE TITLE
evalsha error when rebooting dev redis

### ISSUE THREAD

**Issue by simllll** [wyattjoh/rate-limit-redis#71]
### Description

when rebooting the redis instance on my dev environment, but leave the connection "alive", all requests afterwarsd result into:

ReplyError: NOSCRIPT No matching script. Please use EVAL.
    at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'EVALSHA',
    args: [
      '3f424a504987d231baa2e19159bb5def8ad32f87',
      '1',
      'rl-testing:134.209.252.110:/app-api/',
      '0',
      '1000'
    ]

### Library version

3.0.1

### Node version

16.x

### Typescript version (if you are using it)

16.x

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @simllll,

Sorry for the late response :/

I'm working on this issue, and at first glance a simple fix of reloading the script if this error occurs should work :)

I'll keep you updated on this.

**Comment by gamemaker1** [comment]
Also, which Redis client are you using?

**Comment by simllll** [comment]
ioredis

**Comment by gamemaker1** [comment]
Thanks :)

Also, how did you reboot the Redis instance while leaving the connection alive? I'm running it locally using Docker and `docker restart <container id>` throws a socket error:

```
/.pnpm/@node-redis+client@1.0.4/node_modules/@node-redis/client/dist/lib/client/socket.js:182
                    __classPrivateFieldGet(this, _RedisSocket_instances, "m", _RedisSocket_onSocketError).call(this, new errors_1.SocketClosedUnexpectedlyError());
                                                                                                                     ^
SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at Socket.<anonymous> (/.pnpm/@node-redis+client@1.0.4/node_modules/@node-redis/client/dist/lib/client/socket.js:182:118)
    at Object.onceWrapper (node:events:640:26)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:687:12)
```

**Comment by simllll** [comment]
Mhm, interesting. Never tested it "locally", but I had two cases where this is happening:
1.) we have a ssh tunnel that connects all our services from a local env to the test environment services. also redis, mongodb, etc.. the ssh tunnel was kept alive, but the service behind has been restarted (Redis for example).
2.) on AWS with elasticcloud, there is also a redis service with a "proxy" endpoint, I guess it is similar as the ssh tunnel in this case.

**Comment by luin** [comment]
For the `NOSCRIPT No matching script. Please use EVAL` error, I think the cause was the script cache was cleared when the server restarted.

Personally, I think rate-limit-redis could probably just use `defineCommand` or the `scripts` constructor option to invoke Lua scripts since ioredis handle the cache loading automatically. Refer: https://github.com/luin/ioredis#lua-scripting

**Comment by simllll** [comment]
Regarding the root cause, I also think it is related to the script cache.

`defineCommand` sounds like a very good solution to me too! Can this be done with the "sendCommand" approach?

**Comment by gamemaker1** [comment]
> For the NOSCRIPT No matching script. Please use EVAL error, I think the cause was the script cache was cleared when the server restarted.

Yes, I think so too - hence thought reloading the script on receiving the error might fix it.

> Personally, I think rate-limit-redis could probably just use defineCommand or the scripts constructor option to invoke Lua scripts since ioredis handle the cache loading automatically. Refer: [luin/ioredis#lua-scripting](https://github.com/luin/ioredis#lua-scripting)

That sounds like a great solution! However, we want to allow the user to use any client they prefer - and not all clients provide a `defineCommand` function.

**Comment by gamemaker1** [comment]
I also just realised that I was testing with `node-redis` instead of `ioredis` 🤦🏾

**Comment by gamemaker1** [comment]
Using `ioredis`, I get this:

```[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Caught NOSCRIPT error
```

**Comment by gamemaker1** [comment]
Here's a patch that fixes the issue with IORedis:

```diff
diff --git a/src/lib.ts b/src/lib.ts
index c0c39da..90a012f 100644
--- a/src/lib.ts
+++ b/src/lib.ts
@@ -111,14 +111,25 @@ class RedisStore implements Store {
    * @returns {IncrementResponse} - The number of hits and reset time for that client
    */
   async increment(key: string): Promise<IncrementResponse> {
-    const results = await this.sendCommand(
-      "EVALSHA",
-      await this.loadedScriptSha1,
-      "1",
-      this.prefixKey(key),
-      this.resetExpiryOnChange ? "1" : "0",
-      this.windowMs.toString()
-    );
+    let results;
+    try {
+      results = await this.sendCommand(
+        "EVALSHA",
+        await this.loadedScriptSha1,
+        "1",
+        this.prefixKey(key),
+        this.resetExpiryOnChange ? "1" : "0",
+        this.windowMs.toString()
+      );
+    } catch (error: unknown) {
+      if ((error as Error).message.includes("NOSCRIPT")) {
+        console.log("Caught NOSCRIPT error");
+        this.loadedScriptSha1 = this.loadScript();
+        return this.increment(key);
+      }
+
+      throw error;
+    }
 
     if (!Array.isArray(results)) {
       throw new TypeError("Expected result to be array of values");
```

**Comment by vishald2509** [comment]
This issue still exist

**Comment by 7sa3** [comment]
Can replicate with the following configuration:

**Exception: 
[ioredis] Unhandled error event: Error: connect ECCONREFUSED 127.0.0.1:6379

ReplyError: NOSCRIPT No matching script. Please use EVAL.**

```
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
  standardHeaders: true,
  legacyHeaders: false,

  store: new RedisStore({
    // @ts-expect-error - Known issue: the `call` function is not present in @types/ioredis
    sendCommand: async (...args: string[]) => client.call(...args),
  }),
});
```

**Comment by rajatbhatnagar94** [comment]
Can we get this issue fixed? Everytime Redis is restarted, it is not loading the scripts automatically and hence throws an error.
