### ISSUE TITLE
Rate limiting should be ignored when Redis client is unreachable

### ISSUE THREAD

**Issue by dark-matter-matters** [wyattjoh/rate-limit-redis#72]
### Description

If the Redis client throws an error, such as `` ECONNREFUSED 127.0.0.1:6379``, RedisStore should act as a useless middleware instead of blocking the API where it's being used. Catching the Redis client error does not help since RedisStore will still throw an error about the Redis client. 

### Why

Rate limiting is not vital for an API like a database and it should not prevent it from working in case Redis is unreachable. 

### Alternatives

Catching Redis client errors, catching inside `sendCommand`. 

```js
signalLimiter = rateLimit({
            windowMs: 1 * 60 * 1000,
            max: global.gConfig.MAX_REQUESTS_PER_MINUTE, 
            standardHeaders: true,
            legacyHeaders: false,
            store: new RedisStore({
                sendCommand: (...args) => {
                    try {
                        return redisClient.sendCommand(args);
                    }
                    catch (err) {
                        console.log("An error occurred while sending Redis command", err);
                        return true; // does not work
                    }
                }
            }),
        });
```
Desired behavior when Redis client error occurs: 
```js
signalLimiter ~= (req, res, next) => next();
```

**Comment by gamemaker1** [comment]
Hi @dark-matter-matters,

Sorry for the late response :/

This is definitely a good idea - we could re-add the `passIfNotConnected` option to handle such connection errors. 

> The original reason I had removed that option in https://github.com/wyattjoh/rate-limit-redis/pull/43 was that it was now the developer who handled connection via a client of their own choice, so instead of returning `true`, they could simply return `0` to set the clients count to `0` and continue. That logic was invalidated when we switched from simple `INCR` commands to using `EVALSHA`, and it makes sense to add this option.

@wyattjoh what do you think?

@dark-matter-matters if @wyattjoh approves the idea, would you be interested in working on a PR for this? (or I could do it too :D)

**Comment by kaykhan** [comment]
@dark-matter-matters did this ever get implemented here? Dd you decide to use something else?

**Comment by wyattjoh** [comment]
I agree that an option for `passIfNotConnected` is useful, but may lead to situations where while booting, it may pass traffic through without limiting. Rate limiting from my perspective is a security feature, and this seems akin to saying "if the powers out, just unlock all the doors", which feels like a risk. The opt-in beheviour suggested bia the option seems like the best of both worlds, but I would rather see it only apply after the _first_ connect, or perhaps accept a function that would get the number of attempts where it could adjust the internal state to allow or not.

**Comment by sampok** [comment]
It would be useful to be able to catch Redis errors and handle as needed.

For example when I need to update my Redis, it fails over to a replica using DNS, and the client is still connected to an old node for a while, which doesn't accept writes. In my application it'd be fine to disable rate limiting for the ~5min, instead of having the whole service unavailable.

**Comment by amakhrov** [comment]
> seems akin to saying "if the powers out, just unlock all the doors", which feels like a risk

been in this situation multiple times. so happy that it is how it actually works in the buildings! i wouldn't care for getting locked in or out in this case

**Comment by nfriedly** [comment]
Ok, express-rate-limit v7.4.0 should be released shortly with a new `passOnStoreError` option that allows you to configure the limiter to "fail open" if your redis server goes down.

**Comment by modestaspruckus** [comment]
> Ok, express-rate-limit v7.4.0 should be released shortly with a new `passOnStoreError` option that allows you to configure the limiter to "fail open" if your redis server goes down.

Hello,
We're facing strange async middleware issues with this flag `passOnStoreError` basically if redis store is not accessible (command timeout) - it should go to next middleware. 
In our case it starts to execute next async middleware as expected but after promise is fired inside it - the next middleware starts without waiting until the last one finishes. On debugger basically code execution is jumping between two middlewares.

**Comment by nfriedly** [comment]
That doesn't sound good! Can you file a new issue, and also see if you can make a minimal project that reproduces the issue?
